site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

snowball:
    resource: "@snowballBundle/Resources/config/routing.yml"
    prefix:  /snowball
