<?php

namespace snowballBundle\Entity;

/**
 * gridRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gridRepository extends \Doctrine\ORM\EntityRepository
{
}
